### ISSUE TITLE
Do we need function 'but_last' ?

### ISSUE THREAD

**Issue by nzour** [whsv26/functional#24]
Been thinking about function `but_last`, [like this](but_last)

I am not sure if this function is necessary.
Also we just may code something like this:

```php
$withoutLast = \Fp\Collection\reverse(
    \Fp\Collection\tail(
        \Fp\Collection\reverse($collection)
    )
);

// or simplified version

$withoutLast = reverse(tail(reverse($collection)));
```

Maybe native function `but_last` would be more understandable and less resource consuming?
I would be pleasured to hear your opinion.

**Comment by nzour** [comment]
I just got noticed that you already implemented `\Fn\Functional\pop` function.

But it is bound with Option and non-empty-list.

Not sure if this is useful for any cases.

**Comment by whsv26** [comment]
I don't think it's really all that useful, but can add it nonetheless.

**Comment by whsv26** [comment]
done
