### ISSUE TITLE
Any cases to add @psalm-pure for really pure functions?

### ISSUE THREAD

**Issue by nzour** [whsv26/functional#29]
In some cases it may be useful to use few functions inside pure context.

Example:

```php
/**
 * @psalm-immutable
 */
class Foo
{
    /** 
     * @var list<Bar>
     */
    public array $bars;

    public function __construct(Bar $first, Bar ...$rest)
    {
        // Impure method call issue occurred here (because Foo is immutable, so requires pure context)
        $this->bars = asList([$first], $rest);
    }
}
```

Of course, there are more ways to compile list, but if we have `asList` why wouldn't we use it whenever we want?

I was just thinking about function `asList`, maybe there are few others function that are actually pure but not annotated yet

**Comment by whsv26** [comment]
Are they really pure functions? Consider this example:

```php
$generator = (function () {
    yield 1;
    yield 2;
    yield 3;
    return 4;
})();

$l1 = asList($generator);
$l2 = asList($generator);
```

You will get ```Uncaught Exception: Cannot traverse an already closed generator``` because of you can't rewind generators.

**Comment by nzour** [comment]
I missed the part that iterators are to pure (we also may have iterator that does io-operations)

Also, I think, it couldn't be mutation-free neither.

Thanks for your reply, I thinks this issue is resolved
