### ISSUE TITLE
Partition function type inference issues

### ISSUE THREAD

**Issue by nzour** [whsv26/functional#34]
```php
/**
 * @return list<array{mixed, Either<string, int>}>
 */
function getValues() { ... }
```

```php

$values = getValues();

$res = partition($values, static function (array $v) {
    [, $either] = $v; // type of $v is lost somewhere, it actually is array<TKey: array-key, TValue: mixed>
  
    return $either instanceof Right;
});

// but for $res variable - type inference would work correctly
```

**Comment by whsv26** [comment]
Seems like Psalm can't infer callback parameter type based on type of another argument in general. It can be solved with collection generic classes where partition, map and other methods will already have collection element type information. In this case Psalm can handle inference.  

There is similar problem with map function. 

![image](https://user-images.githubusercontent.com/11776521/126005693-b14cc6c4-1a08-4e07-b2c5-248369f82fc1.png)


Scala has the same inference problem without secondary parameter list for callback.

![image](https://user-images.githubusercontent.com/11776521/126002928-6c723a2b-0e7a-41f9-b0ae-f6b803c7320b.png)
![image](https://user-images.githubusercontent.com/11776521/126002794-185a0022-f733-4419-8d3c-4dbad5a703ac.png)
